// Generated by Xata Codegen 0.30.1. Please do not edit.
import { buildClient } from "@xata.io/client";
import type { BaseClientOptions } from "@xata.io/client";

export type DatabaseSchema = {};

const DatabaseClient = buildClient();

const defaultOptions = {
	databaseURL:
		"https://Huynh-Ngoc-Thien-s-workspace-4gq9m9.eu-central-1.xata.sh/db/upgress-db",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
	constructor(options?: BaseClientOptions) {
		super({ ...defaultOptions, ...options });
	}
}

let instance: XataClient | undefined = undefined;

export const getXataClient = (options?: BaseClientOptions) => {
	if (instance) return instance;

	instance = new XataClient(options);
	return instance;
};
